### ISSUE TITLE
Long album ID

### ISSUE THREAD

**Issue by guillaumeArgiles** [awstudio-paris/Google-Photos-API#2] opened 2018-05-04 22:59 UTC
When album id is too long like 1000000455940756 the line:
$album->setAlbumId((int) $albumElement->id);

must be replace by : 
$album->setAlbumId((string) $albumElement->id);

in album model.

Otherwise all ids will be 2147483647

**Comment by awstudio-paris** [comment] 2018-05-07 08:36
Hi @guizmore ,
Thanks for your feedback! We think that this was caused because you are using a 32 bits php installation. We had fixed you issue in the version 2.0.0, we had to create a major release because it could break compatibility with existing projects that are using the library.

Could you please confirm that the issue is fixed?

Thank you and regards :)

**Comment by awstudio-paris** [comment] 2018-05-15 07:58
We close it, because we don't have new feedback. Should be fixed, please reopen it otherwise. Thanks.

**Closed as completed by awstudio-paris** 2018-05-15 07:58 UTC
